name: build_and_publish_image

env: #TODO() be sure to manually update the image tag!
  IMAGE_TAG: "0.0.1"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  publish-source-twitter-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/community-tech-alliance/source-actblue:latest, community-tech-alliance/source-actblue:$IMAGE_TAG